tar2bids2preproc:
  tarfile: 'tarfiles/{pi,[a-zA-Z]+}_{project,[a-zA-Z]+}_{date,\d{8}}_{prefix}_{subject,[a-zA-Z0-9]+}_{dcmses,\d}.{dcmhash,[A-E0-9]{8}}.tar'

  heuristic: 'resources/cfmm_bold_rest_mirsattari.py'

  exclude_subjects: []
  singularity:
    tar2bids: 'docker://khanlab/tar2bids:v0.1.3'
    gradcorrect: 'docker://khanlab/gradcorrect:v0.0.3'
    fmriprep: 'docker://nipreps/fmriprep:20.2.6'
    freesurfer: '/project/6050199/akhanf/singularity/bids-apps/freesurfer_freesurfer_7.2.0.sif'


  grad_coeff_file: '/project/ctb-akhanf/akhanf/opt/grad/.coeff_AC84.grad'
  fs_license_file: '/project/ctb-akhanf/akhanf/opt/freesurfer/.license'


  pybids_inputs_freesurfer:
    T1w:
      filters:
        suffix: 'T1w'
        extension: '.nii.gz'
        datatype: 'anat'
      wildcards:
        - subject
        - session
        - acquisition
        - run
